; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 3
; RUN: opt -S -loop-reduce < %s | FileCheck %s

;;target datalayout = "e-m:e-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128"
target triple = "aarch64-unknown-linux-gnu"

define dso_local void @_Z9test_qaddu10__SVBool_tPKhPhmm(<vscale x 16 x i1> %pg, ptr nocapture noundef readonly %src_rows, ptr nocapture noundef writeonly %dst_rows, i64 noundef %stride, i64 noundef %count) local_unnamed_addr #0 {
; CHECK-LABEL: define dso_local void @_Z9test_qaddu10__SVBool_tPKhPhmm(
; CHECK-SAME: <vscale x 16 x i1> [[PG:%.*]], ptr nocapture noundef readonly [[SRC_ROWS:%.*]], ptr nocapture noundef writeonly [[DST_ROWS:%.*]], i64 noundef [[STRIDE:%.*]], i64 noundef [[COUNT:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP16_NOT:%.*]] = icmp eq i64 [[COUNT]], 0
; CHECK-NEXT:    br i1 [[CMP16_NOT]], label [[FOR_COND_CLEANUP:%.*]], label [[FOR_BODY_LR_PH:%.*]]
; CHECK:       for.body.lr.ph:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 8 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv8i1(<vscale x 16 x i1> [[PG]])
; CHECK-NEXT:    [[TMP1:%.*]] = tail call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[MUL:%.*]] = shl nuw nsw i64 [[TMP1]], 5
; CHECK-NEXT:    [[TMP2:%.*]] = shl i64 [[TMP1]], 4
; CHECK-NEXT:    [[TMP3:%.*]] = shl i64 [[TMP1]], 3
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.cond.cleanup.loopexit:
; CHECK-NEXT:    br label [[FOR_COND_CLEANUP]]
; CHECK:       for.cond.cleanup:
; CHECK-NEXT:    ret void
; CHECK:       for.body:
; CHECK-NEXT:    [[LSR_IV:%.*]] = phi i64 [ [[LSR_IV_NEXT:%.*]], [[FOR_BODY]] ], [ [[COUNT]], [[FOR_BODY_LR_PH]] ]
; CHECK-NEXT:    [[SRC_ROWS_ADDR_019:%.*]] = phi ptr [ [[SRC_ROWS]], [[FOR_BODY_LR_PH]] ], [ [[ADD_PTR:%.*]], [[FOR_BODY]] ]
; CHECK-NEXT:    [[DST_ROWS_ADDR_018:%.*]] = phi ptr [ [[DST_ROWS]], [[FOR_BODY_LR_PH]] ], [ [[ADD_PTR7:%.*]], [[FOR_BODY]] ]
; CHECK-NEXT:    [[TMP4:%.*]] = tail call <vscale x 16 x i8> @llvm.masked.load.nxv16i8.p0(ptr [[SRC_ROWS_ADDR_019]], i32 1, <vscale x 16 x i1> [[PG]], <vscale x 16 x i8> zeroinitializer), !tbaa [[TBAA6:![0-9]+]]
; CHECK-NEXT:    [[SCEVGEP1:%.*]] = getelementptr i8, ptr [[SRC_ROWS_ADDR_019]], i64 [[TMP2]]
; CHECK-NEXT:    [[TMP5:%.*]] = tail call <vscale x 16 x i8> @llvm.masked.load.nxv16i8.p0(ptr [[SCEVGEP1]], i32 1, <vscale x 16 x i1> [[PG]], <vscale x 16 x i8> zeroinitializer), !tbaa [[TBAA6]]
; CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds i8, ptr [[SRC_ROWS_ADDR_019]], i64 [[STRIDE]]
; CHECK-NEXT:    [[TMP6:%.*]] = tail call <vscale x 16 x i8> @llvm.masked.load.nxv16i8.p0(ptr [[ARRAYIDX2]], i32 1, <vscale x 16 x i1> [[PG]], <vscale x 16 x i8> zeroinitializer), !tbaa [[TBAA6]]
; CHECK-NEXT:    [[SCEVGEP:%.*]] = getelementptr i8, ptr [[ARRAYIDX2]], i64 [[TMP2]]
; CHECK-NEXT:    [[TMP7:%.*]] = tail call <vscale x 16 x i8> @llvm.masked.load.nxv16i8.p0(ptr [[SCEVGEP]], i32 1, <vscale x 16 x i1> [[PG]], <vscale x 16 x i8> zeroinitializer), !tbaa [[TBAA6]]
; CHECK-NEXT:    [[TMP8:%.*]] = tail call <vscale x 16 x i8> @llvm.aarch64.sve.uqadd.x.nxv16i8(<vscale x 16 x i8> [[TMP4]], <vscale x 16 x i8> [[TMP6]])
; CHECK-NEXT:    [[TMP9:%.*]] = tail call <vscale x 16 x i8> @llvm.aarch64.sve.uqadd.x.nxv16i8(<vscale x 16 x i8> [[TMP5]], <vscale x 16 x i8> [[TMP7]])
; CHECK-NEXT:    [[TMP10:%.*]] = bitcast <vscale x 16 x i8> [[TMP8]] to <vscale x 8 x i16>
; CHECK-NEXT:    [[TMP11:%.*]] = trunc <vscale x 8 x i16> [[TMP10]] to <vscale x 8 x i8>
; CHECK-NEXT:    tail call void @llvm.masked.store.nxv8i8.p0(<vscale x 8 x i8> [[TMP11]], ptr [[DST_ROWS_ADDR_018]], i32 1, <vscale x 8 x i1> [[TMP0]]), !tbaa [[TBAA6]]
; CHECK-NEXT:    [[TMP12:%.*]] = bitcast <vscale x 16 x i8> [[TMP9]] to <vscale x 8 x i16>
; CHECK-NEXT:    [[SCEVGEP2:%.*]] = getelementptr i8, ptr [[DST_ROWS_ADDR_018]], i64 [[TMP3]]
; CHECK-NEXT:    [[TMP13:%.*]] = trunc <vscale x 8 x i16> [[TMP12]] to <vscale x 8 x i8>
; CHECK-NEXT:    tail call void @llvm.masked.store.nxv8i8.p0(<vscale x 8 x i8> [[TMP13]], ptr [[SCEVGEP2]], i32 1, <vscale x 8 x i1> [[TMP0]]), !tbaa [[TBAA6]]
; CHECK-NEXT:    [[ADD_PTR]] = getelementptr inbounds i8, ptr [[SRC_ROWS_ADDR_019]], i64 [[MUL]]
; CHECK-NEXT:    [[ADD_PTR7]] = getelementptr inbounds i8, ptr [[DST_ROWS_ADDR_018]], i64 [[MUL]]
; CHECK-NEXT:    [[LSR_IV_NEXT]] = add i64 [[LSR_IV]], -1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[LSR_IV_NEXT]], 0
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label [[FOR_COND_CLEANUP_LOOPEXIT:%.*]], label [[FOR_BODY]], !llvm.loop [[LOOP9:![0-9]+]]
;
entry:
  %cmp16.not = icmp eq i64 %count, 0
  br i1 %cmp16.not, label %for.cond.cleanup, label %for.body.lr.ph

for.body.lr.ph:                                   ; preds = %entry
  %0 = tail call <vscale x 8 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv8i1(<vscale x 16 x i1> %pg)
  %1 = tail call i64 @llvm.vscale.i64()
  %mul = shl nuw nsw i64 %1, 5
  br label %for.body

for.cond.cleanup.loopexit:                        ; preds = %for.body
  br label %for.cond.cleanup

for.cond.cleanup:                                 ; preds = %for.cond.cleanup.loopexit, %entry
  ret void

for.body:                                         ; preds = %for.body.lr.ph, %for.body
  %src_rows.addr.019 = phi ptr [ %src_rows, %for.body.lr.ph ], [ %add.ptr, %for.body ]
  %dst_rows.addr.018 = phi ptr [ %dst_rows, %for.body.lr.ph ], [ %add.ptr7, %for.body ]
  %index.017 = phi i64 [ 0, %for.body.lr.ph ], [ %inc, %for.body ]
  %2 = tail call <vscale x 16 x i8> @llvm.masked.load.nxv16i8.p0(ptr %src_rows.addr.019, i32 1, <vscale x 16 x i1> %pg, <vscale x 16 x i8> zeroinitializer), !tbaa !6
  %3 = getelementptr <vscale x 16 x i8>, ptr %src_rows.addr.019, i64 1
  %4 = tail call <vscale x 16 x i8> @llvm.masked.load.nxv16i8.p0(ptr %3, i32 1, <vscale x 16 x i1> %pg, <vscale x 16 x i8> zeroinitializer), !tbaa !6
  %arrayidx2 = getelementptr inbounds i8, ptr %src_rows.addr.019, i64 %stride
  %5 = tail call <vscale x 16 x i8> @llvm.masked.load.nxv16i8.p0(ptr %arrayidx2, i32 1, <vscale x 16 x i1> %pg, <vscale x 16 x i8> zeroinitializer), !tbaa !6
  %6 = getelementptr <vscale x 16 x i8>, ptr %arrayidx2, i64 1
  %7 = tail call <vscale x 16 x i8> @llvm.masked.load.nxv16i8.p0(ptr %6, i32 1, <vscale x 16 x i1> %pg, <vscale x 16 x i8> zeroinitializer), !tbaa !6
  %8 = tail call <vscale x 16 x i8> @llvm.aarch64.sve.uqadd.x.nxv16i8(<vscale x 16 x i8> %2, <vscale x 16 x i8> %5)
  %9 = tail call <vscale x 16 x i8> @llvm.aarch64.sve.uqadd.x.nxv16i8(<vscale x 16 x i8> %4, <vscale x 16 x i8> %7)
  %10 = bitcast <vscale x 16 x i8> %8 to <vscale x 8 x i16>
  %11 = trunc <vscale x 8 x i16> %10 to <vscale x 8 x i8>
  tail call void @llvm.masked.store.nxv8i8.p0(<vscale x 8 x i8> %11, ptr %dst_rows.addr.018, i32 1, <vscale x 8 x i1> %0), !tbaa !6
  %12 = bitcast <vscale x 16 x i8> %9 to <vscale x 8 x i16>
  %13 = getelementptr <vscale x 8 x i8>, ptr %dst_rows.addr.018, i64 1
  %14 = trunc <vscale x 8 x i16> %12 to <vscale x 8 x i8>
  tail call void @llvm.masked.store.nxv8i8.p0(<vscale x 8 x i8> %14, ptr %13, i32 1, <vscale x 8 x i1> %0), !tbaa !6
  %add.ptr = getelementptr inbounds i8, ptr %src_rows.addr.019, i64 %mul
  %add.ptr7 = getelementptr inbounds i8, ptr %dst_rows.addr.018, i64 %mul
  %inc = add nuw i64 %index.017, 1
  %exitcond.not = icmp eq i64 %inc, %count
  br i1 %exitcond.not, label %for.cond.cleanup.loopexit, label %for.body, !llvm.loop !9
}

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 16 x i8> @llvm.aarch64.sve.uqadd.x.nxv16i8(<vscale x 16 x i8>, <vscale x 16 x i8>) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 8 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv8i1(<vscale x 16 x i1>) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 16 x i1> @llvm.aarch64.sve.ptrue.nxv16i1(i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 16 x i8> @llvm.aarch64.sve.umax.u.nxv16i8(<vscale x 16 x i1>, <vscale x 16 x i8>, <vscale x 16 x i8>) #1

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: read)
declare <vscale x 16 x i8> @llvm.masked.load.nxv16i8.p0(ptr nocapture, i32 immarg, <vscale x 16 x i1>, <vscale x 16 x i8>) #3

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: write)
declare void @llvm.masked.store.nxv8i8.p0(<vscale x 8 x i8>, ptr nocapture, i32 immarg, <vscale x 8 x i1>) #4

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare i64 @llvm.vscale.i64() #5

attributes #0 = { mustprogress nofree norecurse nosync nounwind memory(readwrite, inaccessiblemem: none) uwtable vscale_range(1,16) "frame-pointer"="non-leaf" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="generic" "target-features"="+crc,+dotprod,+fp-armv8,+fullfp16,+lse,+neon,+outline-atomics,+ras,+rcpc,+rdm,+sve,+sve2,+v8.1a,+v8.2a,+v8.3a,+v8.4a,+v8.5a,+v8a,+v9a,-fmv" }
attributes #1 = { mustprogress nocallback nofree nosync nounwind willreturn memory(none) }
attributes #2 = { mustprogress nofree norecurse nosync nounwind memory(read, argmem: readwrite, inaccessiblemem: none) uwtable vscale_range(1,16) "frame-pointer"="non-leaf" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="generic" "target-features"="+crc,+dotprod,+fp-armv8,+fullfp16,+lse,+neon,+outline-atomics,+ras,+rcpc,+rdm,+sve,+sve2,+v8.1a,+v8.2a,+v8.3a,+v8.4a,+v8.5a,+v8a,+v9a,-fmv" }
attributes #3 = { nocallback nofree nosync nounwind willreturn memory(argmem: read) }
attributes #4 = { nocallback nofree nosync nounwind willreturn memory(argmem: write) }
attributes #5 = { nocallback nofree nosync nounwind willreturn memory(none) }

!llvm.module.flags = !{!0, !1, !2, !3, !4}
!llvm.ident = !{!5}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 8, !"PIC Level", i32 2}
!2 = !{i32 7, !"PIE Level", i32 2}
!3 = !{i32 7, !"uwtable", i32 2}
!4 = !{i32 7, !"frame-pointer", i32 1}
!5 = !{!"clang version 18.0.0git"}
!6 = !{!7, !7, i64 0}
!7 = !{!"omnipotent char", !8, i64 0}
!8 = !{!"Simple C++ TBAA"}
!9 = distinct !{!9, !10}
!10 = !{!"llvm.loop.mustprogress"}
!11 = distinct !{!11, !10}
