; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes=loop-vectorize,instcombine -enable-csa-vectorization -S < %s 2>&1 | FileCheck %s --check-prefix=NEON
; RUN: opt -passes=loop-vectorize,instcombine -mattr=+sve -enable-csa-vectorization -S < %s 2>&1 | FileCheck %s --check-prefix=SVE

target triple = "aarch64-linux-gnu"

;; Derived from the RVV tests...
;; Stick to a simple case for now, so we can see what the codegen looks like.

;; Not too bad considering we aren't planting clastb inside the loop yet.
;;
;; .LBB0_4:                                // %vector.ph
;;         mov     x9, #-1                         // =0xffffffffffffffff
;;         mov     z1.s, w2
;;         mov     z0.s, #-1                       // =0xffffffffffffffff
;;         incw    x9
;;         pfalse  p0.b
;;         mov     x10, xzr
;;         ptrue   p1.s
;;         and     x11, x8, x9
;;         sub     x9, x8, x11
;; .LBB0_5:                                // %vector.body
;;                                         // =>This Inner Loop Header: Depth=1
;;         ld1w    { z2.s }, p1/z, [x1, x10, lsl #2]
;;         incw    x10
;;         cmpgt   p2.s, p1/z, z2.s, z1.s
;;         cset    w12, ne
;;         sbfx    x12, x12, #0, #1
;;         whilelo p3.s, xzr, x12
;;         cmp     x9, x10
;;         mov     z0.s, p3/m, z2.s
;;         mov     p0.b, p3/m, p2.b
;;         b.ne    .LBB0_5
;; // %bb.6:                               // %middle.block
;;         mov     w0, #-1                         // =0xffffffff
;;         clastb  w0, p0, w0, z0.s
;;         cbz     x11, .LBB0_9

define i32 @simple_csa_int_select(i32 %N, ptr %data, i32 %a) {
; NEON-LABEL: define i32 @simple_csa_int_select(
; NEON-SAME: i32 [[N:%.*]], ptr [[DATA:%.*]], i32 [[A:%.*]]) {
; NEON-NEXT:  [[ENTRY:.*]]:
; NEON-NEXT:    [[CMP9:%.*]] = icmp sgt i32 [[N]], 0
; NEON-NEXT:    br i1 [[CMP9]], label %[[LOOP_PREHEADER:.*]], label %[[EXIT:.*]]
; NEON:       [[LOOP_PREHEADER]]:
; NEON-NEXT:    [[WIDE_TRIP_COUNT:%.*]] = zext nneg i32 [[N]] to i64
; NEON-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i32 [[N]], 4
; NEON-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; NEON:       [[VECTOR_PH]]:
; NEON-NEXT:    [[N_VEC:%.*]] = and i64 [[WIDE_TRIP_COUNT]], 2147483644
; NEON-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <4 x i32> poison, i32 [[A]], i64 0
; NEON-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <4 x i32> [[BROADCAST_SPLATINSERT]], <4 x i32> poison, <4 x i32> zeroinitializer
; NEON-NEXT:    br label %[[VECTOR_BODY:.*]]
; NEON:       [[VECTOR_BODY]]:
; NEON-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; NEON-NEXT:    [[VEC_PHI:%.*]] = phi <4 x i32> [ splat (i32 -1), %[[VECTOR_PH]] ], [ [[TMP4:%.*]], %[[VECTOR_BODY]] ]
; NEON-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = phi <4 x i1> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP3:%.*]], %[[VECTOR_BODY]] ]
; NEON-NEXT:    [[TMP0:%.*]] = getelementptr inbounds i32, ptr [[DATA]], i64 [[INDEX]]
; NEON-NEXT:    [[WIDE_LOAD:%.*]] = load <4 x i32>, ptr [[TMP0]], align 4
; NEON-NEXT:    [[TMP1:%.*]] = icmp slt <4 x i32> [[BROADCAST_SPLAT]], [[WIDE_LOAD]]
; NEON-NEXT:    [[TMP2:%.*]] = bitcast <4 x i1> [[TMP1]] to i4
; NEON-NEXT:    [[DOTNOT:%.*]] = icmp eq i4 [[TMP2]], 0
; NEON-NEXT:    [[TMP3]] = select i1 [[DOTNOT]], <4 x i1> [[ACTIVE_LANE_MASK]], <4 x i1> [[TMP1]]
; NEON-NEXT:    [[TMP4]] = select i1 [[DOTNOT]], <4 x i32> [[VEC_PHI]], <4 x i32> [[WIDE_LOAD]]
; NEON-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 4
; NEON-NEXT:    [[TMP5:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; NEON-NEXT:    br i1 [[TMP5]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; NEON:       [[MIDDLE_BLOCK]]:
; NEON-NEXT:    [[TMP6:%.*]] = call i32 @llvm.experimental.vector.extract.last.active.v4i32(<4 x i32> [[TMP4]], <4 x i1> [[TMP3]], i32 -1)
; NEON-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[N_VEC]], [[WIDE_TRIP_COUNT]]
; NEON-NEXT:    br i1 [[CMP_N]], label %[[EXIT_LOOPEXIT:.*]], label %[[SCALAR_PH]]
; NEON:       [[SCALAR_PH]]:
; NEON-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], %[[MIDDLE_BLOCK]] ], [ 0, %[[LOOP_PREHEADER]] ]
; NEON-NEXT:    [[BC_MERGE_RDX:%.*]] = phi i32 [ [[TMP6]], %[[MIDDLE_BLOCK]] ], [ -1, %[[LOOP_PREHEADER]] ]
; NEON-NEXT:    br label %[[LOOP:.*]]
; NEON:       [[EXIT_LOOPEXIT]]:
; NEON-NEXT:    [[SPEC_SELECT_LCSSA:%.*]] = phi i32 [ [[SPEC_SELECT:%.*]], %[[LOOP]] ], [ [[TMP6]], %[[MIDDLE_BLOCK]] ]
; NEON-NEXT:    br label %[[EXIT]]
; NEON:       [[EXIT]]:
; NEON-NEXT:    [[T_0_LCSSA:%.*]] = phi i32 [ -1, %[[ENTRY]] ], [ [[SPEC_SELECT_LCSSA]], %[[EXIT_LOOPEXIT]] ]
; NEON-NEXT:    ret i32 [[T_0_LCSSA]]
; NEON:       [[LOOP]]:
; NEON-NEXT:    [[IV:%.*]] = phi i64 [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; NEON-NEXT:    [[T_010:%.*]] = phi i32 [ [[BC_MERGE_RDX]], %[[SCALAR_PH]] ], [ [[SPEC_SELECT]], %[[LOOP]] ]
; NEON-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds nuw i32, ptr [[DATA]], i64 [[IV]]
; NEON-NEXT:    [[TMP7:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; NEON-NEXT:    [[CMP1:%.*]] = icmp slt i32 [[A]], [[TMP7]]
; NEON-NEXT:    [[SPEC_SELECT]] = select i1 [[CMP1]], i32 [[TMP7]], i32 [[T_010]]
; NEON-NEXT:    [[IV_NEXT]] = add nuw nsw i64 [[IV]], 1
; NEON-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[IV_NEXT]], [[WIDE_TRIP_COUNT]]
; NEON-NEXT:    br i1 [[EXITCOND_NOT]], label %[[EXIT_LOOPEXIT]], label %[[LOOP]], !llvm.loop [[LOOP3:![0-9]+]]
;
; SVE-LABEL: define i32 @simple_csa_int_select(
; SVE-SAME: i32 [[N:%.*]], ptr [[DATA:%.*]], i32 [[A:%.*]]) #[[ATTR0:[0-9]+]] {
; SVE-NEXT:  [[ENTRY:.*]]:
; SVE-NEXT:    [[CMP9:%.*]] = icmp sgt i32 [[N]], 0
; SVE-NEXT:    br i1 [[CMP9]], label %[[LOOP_PREHEADER:.*]], label %[[EXIT:.*]]
; SVE:       [[LOOP_PREHEADER]]:
; SVE-NEXT:    [[WIDE_TRIP_COUNT:%.*]] = zext nneg i32 [[N]] to i64
; SVE-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; SVE-NEXT:    [[TMP1:%.*]] = shl i64 [[TMP0]], 2
; SVE-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ugt i64 [[TMP1]], [[WIDE_TRIP_COUNT]]
; SVE-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; SVE:       [[VECTOR_PH]]:
; SVE-NEXT:    [[TMP2:%.*]] = call i64 @llvm.vscale.i64()
; SVE-NEXT:    [[TMP3:%.*]] = shl i64 [[TMP2]], 2
; SVE-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[WIDE_TRIP_COUNT]], [[TMP3]]
; SVE-NEXT:    [[N_VEC:%.*]] = sub nsw i64 [[WIDE_TRIP_COUNT]], [[N_MOD_VF]]
; SVE-NEXT:    [[TMP4:%.*]] = call i64 @llvm.vscale.i64()
; SVE-NEXT:    [[TMP5:%.*]] = shl i64 [[TMP4]], 2
; SVE-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 4 x i32> poison, i32 [[A]], i64 0
; SVE-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 4 x i32> [[BROADCAST_SPLATINSERT]], <vscale x 4 x i32> poison, <vscale x 4 x i32> zeroinitializer
; SVE-NEXT:    br label %[[VECTOR_BODY:.*]]
; SVE:       [[VECTOR_BODY]]:
; SVE-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; SVE-NEXT:    [[VEC_PHI:%.*]] = phi <vscale x 4 x i32> [ splat (i32 -1), %[[VECTOR_PH]] ], [ [[TMP10:%.*]], %[[VECTOR_BODY]] ]
; SVE-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = phi <vscale x 4 x i1> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP9:%.*]], %[[VECTOR_BODY]] ]
; SVE-NEXT:    [[TMP6:%.*]] = getelementptr inbounds i32, ptr [[DATA]], i64 [[INDEX]]
; SVE-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 4 x i32>, ptr [[TMP6]], align 4
; SVE-NEXT:    [[TMP7:%.*]] = icmp slt <vscale x 4 x i32> [[BROADCAST_SPLAT]], [[WIDE_LOAD]]
; SVE-NEXT:    [[TMP8:%.*]] = call i1 @llvm.vector.reduce.or.nxv4i1(<vscale x 4 x i1> [[TMP7]])
; SVE-NEXT:    [[TMP9]] = select i1 [[TMP8]], <vscale x 4 x i1> [[TMP7]], <vscale x 4 x i1> [[ACTIVE_LANE_MASK]]
; SVE-NEXT:    [[TMP10]] = select i1 [[TMP8]], <vscale x 4 x i32> [[WIDE_LOAD]], <vscale x 4 x i32> [[VEC_PHI]]
; SVE-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP5]]
; SVE-NEXT:    [[TMP11:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; SVE-NEXT:    br i1 [[TMP11]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; SVE:       [[MIDDLE_BLOCK]]:
; SVE-NEXT:    [[TMP12:%.*]] = call i32 @llvm.experimental.vector.extract.last.active.nxv4i32(<vscale x 4 x i32> [[TMP10]], <vscale x 4 x i1> [[TMP9]], i32 -1)
; SVE-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[N_MOD_VF]], 0
; SVE-NEXT:    br i1 [[CMP_N]], label %[[EXIT_LOOPEXIT:.*]], label %[[SCALAR_PH]]
; SVE:       [[SCALAR_PH]]:
; SVE-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], %[[MIDDLE_BLOCK]] ], [ 0, %[[LOOP_PREHEADER]] ]
; SVE-NEXT:    [[BC_MERGE_RDX:%.*]] = phi i32 [ [[TMP12]], %[[MIDDLE_BLOCK]] ], [ -1, %[[LOOP_PREHEADER]] ]
; SVE-NEXT:    br label %[[LOOP:.*]]
; SVE:       [[EXIT_LOOPEXIT]]:
; SVE-NEXT:    [[SPEC_SELECT_LCSSA:%.*]] = phi i32 [ [[SPEC_SELECT:%.*]], %[[LOOP]] ], [ [[TMP12]], %[[MIDDLE_BLOCK]] ]
; SVE-NEXT:    br label %[[EXIT]]
; SVE:       [[EXIT]]:
; SVE-NEXT:    [[T_0_LCSSA:%.*]] = phi i32 [ -1, %[[ENTRY]] ], [ [[SPEC_SELECT_LCSSA]], %[[EXIT_LOOPEXIT]] ]
; SVE-NEXT:    ret i32 [[T_0_LCSSA]]
; SVE:       [[LOOP]]:
; SVE-NEXT:    [[IV:%.*]] = phi i64 [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; SVE-NEXT:    [[T_010:%.*]] = phi i32 [ [[BC_MERGE_RDX]], %[[SCALAR_PH]] ], [ [[SPEC_SELECT]], %[[LOOP]] ]
; SVE-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[DATA]], i64 [[IV]]
; SVE-NEXT:    [[TMP13:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; SVE-NEXT:    [[CMP1:%.*]] = icmp slt i32 [[A]], [[TMP13]]
; SVE-NEXT:    [[SPEC_SELECT]] = select i1 [[CMP1]], i32 [[TMP13]], i32 [[T_010]]
; SVE-NEXT:    [[IV_NEXT]] = add nuw nsw i64 [[IV]], 1
; SVE-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[IV_NEXT]], [[WIDE_TRIP_COUNT]]
; SVE-NEXT:    br i1 [[EXITCOND_NOT]], label %[[EXIT_LOOPEXIT]], label %[[LOOP]], !llvm.loop [[LOOP3:![0-9]+]]
;
entry:
  %cmp9 = icmp sgt i32 %N, 0
  br i1 %cmp9, label %loop.preheader, label %exit

loop.preheader:                               ; preds = %entry
  %wide.trip.count = zext i32 %N to i64
  br label %loop

exit:                                 ; preds = %loop, %entry
  %t.0.lcssa = phi i32 [ -1, %entry ], [ %spec.select, %loop ]
  ret i32 %t.0.lcssa

loop:                                         ; preds = %loop.preheader, %loop
  %iv = phi i64 [ 0, %loop.preheader ], [ %iv.next, %loop ]
  %t.010 = phi i32 [ -1, %loop.preheader ], [ %spec.select, %loop ]
  %arrayidx = getelementptr inbounds i32, ptr %data, i64 %iv
  %0 = load i32, ptr %arrayidx, align 4
  %cmp1 = icmp slt i32 %a, %0
  %spec.select = select i1 %cmp1, i32 %0, i32 %t.010
  %iv.next = add nuw nsw i64 %iv, 1
  %exitcond.not = icmp eq i64 %iv.next, %wide.trip.count
  br i1 %exitcond.not, label %exit, label %loop
}
;.
; NEON: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]]}
; NEON: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; NEON: [[META2]] = !{!"llvm.loop.unroll.runtime.disable"}
; NEON: [[LOOP3]] = distinct !{[[LOOP3]], [[META2]], [[META1]]}
;.
; SVE: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]]}
; SVE: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; SVE: [[META2]] = !{!"llvm.loop.unroll.runtime.disable"}
; SVE: [[LOOP3]] = distinct !{[[LOOP3]], [[META2]], [[META1]]}
;.
